server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://mysql.macacolabs.site:3322/newsdb
    username: nnl
    password: nnl1234
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari: # 병렬 처리에 강한 커넥션 풀 설정
      maximum-pool-size: 10 # 최대 동시 크롤링 요청 수(= MAX_CONCURRENT_REQUESTS 이상으로)
      minimum-idle: 3 # 초기 요청 수(INITIAL_CONCURRENT_REQUESTS 이상으로)
      idle-timeout: 30000 # 30초 후 유휴 커넥션 정리
      max-lifetime: 600000 # 커넥션 최대 수명: 10분
      connection-timeout: 20000 # 연결 타임아웃: 20초 (크롤링 로직과 동일)
      validation-timeout: 5000

  jpa:
    hibernate:
      ddl-auto: update # 또는 none, validate, create-drop 등
    show-sql: false # SQL 로그 비활성화
    properties:
      hibernate:
        format_sql: false
        show_sql: false
        use_sql_comments: false

# 로그 레벨 설정
logging:
  level:
    org.hibernate: OFF
    org.springframework.orm: OFF
    org.springframework.transaction: OFF
    org.springframework.data: OFF
    com.zaxxer.hikari: WARN
    root: WARN
    com.news.news_crawler_similar_check: INFO

  task:
    execution:
      pool:
        core-size: 3 # INITIAL_CONCURRENT_REQUESTS
        max-size: 6 # MAX_CONCURRENT_REQUESTS
        queue-capacity: 100 # 크롤링 요청 대기 큐
      thread-name-prefix: crawler-
